version: "3.9"

services:
  postgres:
    container_name: postgres
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-network

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.18
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=postgres
      - PGADMIN_DEFAULT_PASSWORD=postgres
      - PGADMIN_LISTEN_PORT=80
    ports:
      - "8080:80"

  backend:
    container_name: backend
    ports:
      - 3000:3000
    build: ./backend
    environment:
      API_PORT: 3000 # must be same as ports
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DBNAME: docker
    restart: always
    networks:
      - dev-network
    depends_on:
      - postgres

networks:
  # Create a new Docker network.
  dev-network:
    driver: bridge
